### ISSUE TITLE
Can't build LD with Carthage and Xcode 10

### ISSUE THREAD

**Issue by ahmedkamohamed** [launchdarkly/ios-client-sdk#145]
Hi Guys,

We are using Carthage to include LD and we started seeing a problem starting Xcode 10 beta. Now we upgraded to Xcode 10 and we still see the same problem while building the scheme.

Xcode 10
Carthage 0.3
LD 2.10.1

```
Task failed with exit code 65:
    /usr/bin/xcrun xcodebuild -workspace /Users/******/Projects/mob-b2c-ios/Carthage/Checkouts/ios-
client/Darkly.xcworkspace -scheme Darkly_iOS -configuration Release -derivedDataPath 
/Users/*******/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/ios-client/2.10.1 -
sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= 
CARTHAGE=YES archive -archivePath /var/folders/d1/_csxf5r52j9c3fcs3n8s2vt1dh09sb/T/ios-client
 SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO 
CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO 
```

Please let us know if you are aware of this problem or have a fix on the roadmap.

Thanks

**Comment by arun251** [comment]
Hi @ahmedkamohamed , we haven't made updates for Xcode 10 beta. Can you try with Xcode 9.4.1?

**Comment by kemalenver** [comment]
Same issue here.  It works with Xcode 9.4.1, but we want to update to 10 so that's not a lot of help.  This is the last framework that we need updated.

**Comment by arun251** [comment]
OK, we'll tackle it next week.

**Comment by ahmedkamohamed** [comment]
Hi @arun251 yes there are no problems with Xcode 9.4.1 but we needed to upgrade to Xcode because of other features we have.

Thank you for the instant reply :).. Will be waiting for the release!

**Comment by jazz-mobility** [comment]
@arun251 This is a release blocker for us for iOS 12 release, can you please prioritize it. We are facing this issue while building with Carthage.

**Comment by ethanjdiamond** [comment]
@arun251 Any updates on this? It's the last library blocking us from upgrading as well.

**Comment by arun251** [comment]
We should have a fix for this in 2.13.5, released just now. Let us know if that doesn't work for you.

**Comment by huyduc** [comment]
```
The following build commands failed:
	CompileC /Users/luonghuyduc/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/ios-client/2.13.5/Build/Intermediates.noindex/ArchiveIntermediates/Darkly_iOS/IntermediateBuildFilesPath/Darkly.build/Release-iphoneos/Darkly_iOS.build/Objects-normal/armv7/LDUserModel.o /Users/luonghuyduc/Documents/Work/Carousell-iOS/Carthage/Checkouts/ios-client/Darkly/LDUserModel.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

Am I the only one still getting compile error?

**Comment by jbfitbit** [comment]
I've checked out 2.13.5 and master and 2.14, but I'm still seeing this error:

```
Build system information
error: Multiple commands produce '/Users/me/build/sandbox/Release/Build/Products/Release-iphonesimulator/Darkly.framework/Darkly':
1) Target 'Darkly_iOS' has a command with output '/Users/me/build/sandbox/Release/Build/Products/Release-iphonesimulator/Darkly.framework/Darkly'
2) Target 'Darkly_osx' has a command with output '/Users/me/build/sandbox/Release/Build/Products/Release-iphonesimulator/Darkly.framework/Darkly'
```

**Comment by jbfitbit** [comment]
https://github.com/launchdarkly/ios-client/pull/160/files

**Comment by JPMOB** [comment]
Is there any update on this issue. Even I'm facing the same trouble.
The `#import "Darkly.h"` results in file not found.

What is the alternate here?
@arun251, Appreciate your help here.

**Comment by jazz-mobility** [comment]
@JPMOB `@import Darkly;` should work here.

**Comment by arun251** [comment]
@jbfitbit @JPMOB We released version 2.14.4, which should resolve this issue. Please let me know if you're still running into this issue.

**Comment by jbfitbit** [comment]
I am still seeing this issue on 2.14.4. My PR that was just closed had a fix that worked.

**Comment by arun251** [comment]
Thanks for the update @jbfitbit . I don't think we closed the PR, but GitHub may be reporting a new merge conflict.

**Comment by JPMOB** [comment]
@arun251 We can not use latest version of LD that need more effort and process, can you provide some way to fix the older version (2.1.3), 

We are keep getting LD file  not found even after @import

**Comment by JPMOB** [comment]
> @jbfitbit @JPMOB We released version 2.14.4, which should resolve this issue. Please let me know if you're still running into this issue.

@arun251 We can not use latest version of LD that need more effort and process, can you provide some way to fix the older version (2.1.3),

We are keep getting LD file not found even after @import

**Comment by ridvank** [comment]
Same problem occurs in XCode 10.2 as well.

**Comment by gabrieloc** [comment]
ETA on Xcode 10.2 support?

**Comment by jbfitbit** [comment]
I think the issue is that framework names have to be different between the build targets.

**Comment by JUSTINMKAUFMAN** [comment]
Bump on Xcode 10.2 support...

**Comment by markpokornycos** [comment]
Here are 2 potential work-arounds you might try:

**Limit Carthage Platform**
If your project runs on only 1 platform, limit the Carthage build to that platform. Run `carthage update --platform ios | watchos | osx | tvos` choosing exactly one platform. If you need multiple platforms then build them one at a time. Once Carthage has built the LD framework(s), your project build should just be linking to them. 
For iOS builds, build the watch first…that way when iOS builds and links to the watch its already there.

**Rename LD Frameworks**
Manually change the LD SDK project to rename the built product to `Darkly_<platform>`. You can leave one platform's framework name unchanged, then change the remaining platforms needed. 
1. Open Darkly.xcodeproj. Be sure not to open the workspace.
2. Select the `Darkly` project in the Project Navigator.
3. Select the platform target
4. Open Build Settings.
5. Find `Product Name` under Packaging. 
6. Change the Product Name to `Darkly_<platform>`
7. Clean & Build that platform's target. Verify the new framework name appears in the `Product` group in the Project Navigator. 
8. Repeat steps 3 - 7 for each platform to rename.
9. Run `carthage build`. Verify the renamed frameworks appear in the Carthage/Build directory.
10. In the client app project, for each of the platform targets that were renamed, remove the original `Darkly.framework` and add the new `Darkly_<platform>` framework.
11. Replace any imports for renamed Darkly frameworks. If code is shared between multiple platforms, add conditional compiler directives to import the correct framework name for the platform.
12. Build each target. Verify the build succeeds.

FWIW: I am not seeing the build errors either in Carthage or Xcode 10.1. So I can't be sure the above workarounds will work. Renaming the frameworks follows the suggestion @jbfitbit made, and it works for me on the v3 beta, but since I'm not seeing the issue at all I can't be sure it will work in your case.

**Comment by ethanjdiamond** [comment]
Thanks @markpokornycos. We have a script pulling this down for our build servers so we don't have the option of manually going into your project and changing it. Do you have an ETA on when a release with the fixed issue would be done?

**Comment by markpokornycos** [comment]
We hope to go to work on this next week and release late next week. Our intent is to leave the iOS framework name unchanged. Changing the framework names for watchOS, macOS, and tvOS will require client app changes for apps supporting those platforms.

**Comment by jazz-mobility** [comment]
@markpokornycos Any updates on Xcode 10.2 support?

**Comment by jbfitbit** [comment]
My pull request should work with the new build system. Feel free to reference the branch. I just rebased with master: https://github.com/launchdarkly/ios-client/pull/160

https://github.com/jbfitbit/ios-client/tree/FixForXcode10

**Comment by torchhound** [comment]
Both iOS SDK client version 3 and 4 should work with Xcode 10.2.1
